package adt;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class ListOfStringsImmutableTest {

    IListOfStringsImmutable empty;
    IListOfStringsImmutable aList;

    @Before
    public void setUp() throws Exception {
        empty = ListOfStringsImmutable.createEmpty();
        aList = ListOfStringsImmutable.createEmpty();
        aList = aList.add("A");
        aList = aList.add("B");
    }

    // DOESN'T TEST IMMUTABILITY!

    @Test
    public void insert() {
        aList = aList.insert("C", 0);
        aList = aList.insert("D", 1);
        IListOfStringsImmutable copy = new ListOfStringsImmutable();
        copy = copy.add("C");
        copy = copy.add("D");
        copy = copy.add("A");
        copy = copy.add("B");
        assertTrue(aList.equals(copy));
    }

    @Test (expected = IndexOutOfBoundsException.class)
    public void testInsertOutOfBounds() {
        aList = aList.insert("C", 3);
    }

    @Test (expected = IndexOutOfBoundsException.class)
    public void testInsertNegative() {
        aList = aList.insert("C", -1);
    }

    @Test
    public void get() {
        assertEquals("A", aList.get(0));
        assertEquals("B", aList.get(1));
    }

    @Test (expected = IndexOutOfBoundsException.class)
    public void getOutOfBounds() {
        empty.get(0);
    }

    @Test
    public void remove() {
        aList = aList.remove("B");
        aList = aList.remove("A");
        // If the autogenerated equals is used, this test fails. Can you tell why?
        assertTrue(aList.equals(empty));
    }

    @Test
    public void removeNoExist() {
        empty = empty.remove("A");
        assertTrue(empty.equals(ListOfStringsImmutable.createEmpty()));

    }

    @Test
    public void size() {
        assertTrue(aList.size() == 2);
        assertTrue(empty.size() == 0);
    }

    @Test
    public void testEquals() {
        assertTrue(empty.equals(empty));
        assertFalse(empty.equals(aList));
        assertFalse(empty.equals(null));
        assertFalse(empty.equals(""));
        IListOfStringsImmutable reverse = new ListOfStringsImmutable();
        reverse = reverse.add("B");
        reverse = reverse.add("A");
        assertFalse(reverse.equals(aList));
    }

    @Test
    public void testHashcode() {
        // If the autogenerated hashCode is used, THIS TEST FAILS! Can you tell why?
        empty = empty.add("A");
        empty = empty.add("B");
        empty = empty.remove("A");
        empty = empty.remove("B");
        assertTrue(empty.hashCode() == ListOfStringsImmutable.createEmpty().hashCode());
    }
}